# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Category.create!([
  { :title => "Dining Out", :created_at => "2013-11-28 02:10:40", :updated_at => "2013-11-28 02:10:40" },
  { :title => "Groceries", :created_at => "2013-11-28 02:10:40", :updated_at => "2013-11-28 02:10:40" },
  { :title => "Alcohol", :created_at => "2013-11-28 02:10:40", :updated_at => "2013-11-28 02:10:40" },
  { :title => "Take-Out", :created_at => "2013-11-28 02:10:40", :updated_at => "2013-11-28 02:10:40" },
  { :title => "Public Transportation", :created_at => "2013-11-28 02:10:40", :updated_at => "2013-11-28 02:10:40" },
  { :title => "Cabs/Taxis", :created_at => "2013-11-28 02:10:40", :updated_at => "2013-11-28 02:10:40" },
  { :title => "Clothing", :created_at => "2013-11-28 02:10:40", :updated_at => "2013-11-28 02:10:40" },
  { :title => "Out of Town Travel", :created_at => "2013-11-28 02:10:40", :updated_at => "2013-11-28 02:10:40" },
  { :title => "Cell Phone", :created_at => "2013-11-28 02:10:40", :updated_at => "2013-11-28 02:10:40" },
  { :title => "Rent", :created_at => "2013-11-28 02:10:40", :updated_at => "2013-11-28 02:10:40" },
  { :title => "Utilities", :created_at => "2013-11-28 02:10:40", :updated_at => "2013-11-28 02:10:40" },
  { :title => "Books", :created_at => "2013-11-28 02:10:40", :updated_at => "2013-11-28 02:10:40" },
  { :title => "Gym", :created_at => "2013-11-28 02:10:40", :updated_at => "2013-11-28 02:10:40" },
  { :title => "Misc.", :created_at => "2013-11-28 02:10:40", :updated_at => "2013-11-28 02:10:40" }
])



Expense.create!([
  { :user_id => 2, :category_id => 3, :amount => 4050, :created_at => "2013-11-28 02:14:23", :updated_at => "2013-11-28 02:14:23" },
  { :user_id => 2, :category_id => 13, :amount => 12000, :created_at => "2013-11-28 02:14:37", :updated_at => "2013-11-28 02:14:37" }
])



Friendship.create!([
  { :user_id => 2, :friend_id => 1, :created_at => "2013-11-28 02:13:38", :updated_at => "2013-11-28 02:13:38", :accepted => true },
  { :user_id => 1, :friend_id => 2, :created_at => "2013-11-28 02:13:38", :updated_at => "2013-11-28 02:13:54", :accepted => true }
])



User.create!([
  { :name => "Amanda Himmelstoss", :email => "ahimmelstoss@gmail.com", :facebook_id => nil, :facebook_token => nil, :created_at => "2013-11-28 02:11:07", :updated_at => "2013-11-28 02:11:07", :remember_token => "e011b815fd1bd27ad806e70b8fba5bde9710f384", :provider => "facebook", :uid => "1343310232", :info => {"nickname"=>"ahimmelstoss", "email"=>"ahimmelstoss@gmail.com", "name"=>"Amanda Himmelstoss", "first_name"=>"Amanda", "last_name"=>"Himmelstoss", "image"=>"http://graph.facebook.com/1343310232/picture?type=square", "urls"=>{"Facebook"=>"https://www.facebook.com/ahimmelstoss"}, "location"=>"Brooklyn, New York", "verified"=>true}, :username => "ahimmelstoss" },
  { :name => "Alex Hioreanu", :email => "hioreanu@gmail.com", :facebook_id => nil, :facebook_token => nil, :created_at => "2013-11-28 02:13:32", :updated_at => "2013-11-28 02:13:32", :remember_token => "d2901c8cb0173a6f6ad9b220a1d439accf75965a", :provider => "facebook", :uid => "1536072019", :info => {"nickname"=>"hioreanu", "email"=>"hioreanu@gmail.com", "name"=>"Alex Hioreanu", "first_name"=>"Alex", "last_name"=>"Hioreanu", "image"=>"http://graph.facebook.com/1536072019/picture?type=square", "urls"=>{"Facebook"=>"https://www.facebook.com/hioreanu"}, "location"=>"Brooklyn, New York", "verified"=>true}, :username => "hioreanu" }
])


